name: Lint and Test

# Runs TS type checks, linting, and tests for a push to any branch.
# TODO Actually implement TS type checks, linting, and tests
# TODO Figure out a way to run lints/tests on forked repo PRs, but NOT expose
# any kind of secrets (eg if we use a GitHub Action for NPM publishing).
on: push

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node/NPM
        uses: actions/setup-node@v3
        with:
          # Just picked what we've been using in local dev work
          node-version: 18
      - name: Install node modules
        # `npm ci` tells npm to install matching against package-lock file
        run: npm ci
      # From here down is actual linting/testing of code.
      # We could run these in parallel for speed, but easiest to just run
      # sequentially for now and it makes subject of error a bit more readable.
      - name: Lint code for syntax and problems
        run: npm run lint-code-ci
      - name: Lint code for styling
        run: npm run lint-formatting-ci
